spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:54329/handmade}
    username: ${DB_USERNAME:fur}
    password: ${DB_PASSWORD:lucis}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate

  liquibase:
    changeLog: classpath:/db/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: true

jwt:
  secret: furlucis
  expiration: 604800000
